# Generated by Django 3.1.6 on 2021-02-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='Assessment_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='Evaluation_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='Expiration_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Date_Board_Resolution',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Due_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Evaluation_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='Request_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
